/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import Vista.*;
import Controlador.cCliente;
import Modelo.mUser;
import Controlador.cUser;
import Modelo.Valida;
import Modelo.crypt;
import Aplicacion.Application;
import Modelo.mCliente;
import Aplicacion.Application;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.util.UIScale;
import java.applet.Applet;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import raven.toast.Notifications;

/**
 *
 * @author Fran
 */
public class LoginForm extends javax.swing.JPanel {

    /**
     * Creates new form pnlLogin
     */
    private mUser modeloUser;
    private cUser controladorUser;
    crypt cry = new crypt();

    private int idTipoUs;
    private int idUsers;
    private int idCuenta;

    public LoginForm() {
        initComponents();
        init();

        txtUser7.setDocument(new Valida(30, "[a-zA-Z0-9]*"));
        txtContra7.setDocument(new Valida(12, "[a-zA-Z0-9]*"));
    }

    private void init() {

        txtContra7.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true;"
                + "showCapsLock:true");
        txtUser7.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Usuario");
        txtContra7.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Contraseña");
    }

    private void limpiarCampos() {
        txtUser7.setText("");
        txtContra7.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        pLogin2 = new com.k33ptoo.components.KGradientPanel();
        txtUser7 = new javax.swing.JTextField();
        imgContr7 = new javax.swing.JLabel();
        imgUser7 = new javax.swing.JLabel();
        btnRecuperar7 = new javax.swing.JLabel();
        btnRegistro7 = new javax.swing.JLabel();
        txtContra7 = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgapp.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 770));

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkGradientFocus(90);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 189, 97));

        pLogin2.setkBorderRadius(0);
        pLogin2.setkEndColor(new java.awt.Color(255, 255, 204));
        pLogin2.setkFillBackground(false);
        pLogin2.setkGradientFocus(54);
        pLogin2.setkStartColor(new java.awt.Color(204, 255, 255));

        imgContr7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/padlock (2).png"))); // NOI18N

        imgUser7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        imgUser7.setMaximumSize(new java.awt.Dimension(86, 101));
        imgUser7.setMinimumSize(new java.awt.Dimension(86, 101));

        btnRecuperar7.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        btnRecuperar7.setForeground(new java.awt.Color(0, 153, 0));
        btnRecuperar7.setText("¿Olvido su contraseña?");
        btnRecuperar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuperarMouseClicked(evt);
            }
        });

        btnRegistro7.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        btnRegistro7.setForeground(new java.awt.Color(0, 153, 0));
        btnRegistro7.setText("Registrarse");
        btnRegistro7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLogin2Layout = new javax.swing.GroupLayout(pLogin2);
        pLogin2.setLayout(pLogin2Layout);
        pLogin2Layout.setHorizontalGroup(
            pLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogin2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgUser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgContr7))
                .addGroup(pLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLogin2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContra7, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pLogin2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(pLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecuperar7))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistro7)
                .addGap(218, 218, 218))
        );
        pLogin2Layout.setVerticalGroup(
            pLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogin2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txtUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(txtContra7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecuperar7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistro7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(imgContr7)
                .addGap(185, 185, 185))
        );

        jLabel15.setDisplayedMnemonic('B');
        jLabel15.setFont(new java.awt.Font("Niagara Engraved", 0, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Bienvenido al sistema de RsCars");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(pLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(pLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 780, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        limpiarCampos();
        Application.registro();
    }//GEN-LAST:event_btnRegistroMouseClicked

    private void btnRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarMouseClicked
        limpiarCampos();
        Application.Actualizar();
    }//GEN-LAST:event_btnRecuperarMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        try {
            try {
                cUser ct = new cUser();
                ct.usuario = txtUser7.getText();
                ct.contra = txtContra7.getText();
                ct.contra = cry.encryptPassword(txtContra7.getText());
                ResultSet rs = ct.Login();
                if (rs.next()) {
                    idTipoUs = rs.getInt("idTipo");
                    idUsers = rs.getInt("idUsuario");
                    rs.close();
                    SelectID();
                } else {
                    Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER, "Credenciales incorrectas");
                }

            } catch (SQLException ex) {
                System.out.println(ex.toString() + " ERROR");
            }

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    public void SelectID() throws SQLException {
        try {
            cUser ctUser = new cUser();
            ctUser.idtipoUser = idTipoUs;
            ctUser.idUser = idUsers;
            ResultSet rs = ctUser.SelecionarNivel();

            if (rs.next()) {
                if (idTipoUs == 1) {
                    idCuenta = rs.getInt("idUsuario");
                    limpiarCampos();
                    Application.login();
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Bienvenido al sistema");
                }
                if (idTipoUs == 2) {
                    idCuenta = rs.getInt("idUsuario");
                    limpiarCampos();
                    Application.loginMeca();
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Bienvenido al sistema");

                }
                if (idTipoUs == 3) {
                    idCuenta = rs.getInt("idUsuario");

                }
                if (idTipoUs == 4) {
                    idCuenta = rs.getInt("idUsuario");

                }

                rs.close();

                this.dispose();
            } else {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "No se encontro");
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel btnRecuperar7;
    private javax.swing.JLabel btnRegistro7;
    private javax.swing.JLabel imgContr7;
    private javax.swing.JLabel imgUser7;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel pLogin2;
    private javax.swing.JPasswordField txtContra7;
    public javax.swing.JTextField txtUser7;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
